### ISSUE TITLE
Package compatibility caps

### ISSUE THREAD

**Issue by KZiemian** [JuliaStrings/ICU.jl#30]
Ref: https://discourse.julialang.org/t/package-compatibility-caps/15301

**Comment by StefanKarpinski** [comment]
I'm not sure how it's valid... the cap is correct, afaict, ICU does not support 0.7/1.0, so the only action to be taken is to release a new version of ICU that does support the new Julia version.

**Comment by ScottPJones** [comment]
Why does JuliaStrings/ICU.jl even exist?  It was made from the already superseded nolta/ICU.jl, which hadn't been maintained in years. @nalimilan had repointed it to JuliaString/ICU.jl, and yes, it's only supported up to v0.6.

**Comment by StefanKarpinski** [comment]
Agree, the fixes in `JuliaString/ICU.jl` should be backported to this, the original repo for ICU and then this should be made the official source of the package again.
